---


- name: Pull shinyApp from git via Rscript launch_Demo.R
  hosts: shinyservers
  remote_user: "{{ superuser }}"
  gather_facts: no
  #where do all the developers R-libs go? ->   R_LIBS_USER
  environment:
          R_LIBS_USER: /home/{{ developer }}/R/lib
  tags: developer_tasks

  tasks:

    - name: create the user developer
      ansible.builtin.user:
        name: "{{ developer }}"
        shell: /bin/bash
        create_home: YES
        #groups: admins,developers
        password: "{{ developer_password | password_hash('sha512') }}"
        append: yes

    - name: Install R-packages
      # since I don't think .bash_profile is sourced, set environment
      #command: R -e "install.packages(c{{R_pkgs}}, repos='http://cran.rstudio.com/')" > /dev/tcp/localhost/4000 2>&1
      command: R -e "install.packages(c{{R_pkgs}}, repos='http://cran.rstudio.com/')"
      #async: 45
      #poll: 5

    - name: launch_Demo.R - require devtools
      command: R -e "require('devtools')"

    - name: launch_Demo.R - install_github
      command: R -e "devtools::install_github( repo = 'kulmak/AIROW.demo', force = TRUE )"

    - name: run launch_Demo.R - service:"{{ shinyApp_port }}"
      # command: nohup R -e "AIROW.demo::run_app(options = list(port = "{{ shinyApp_port }}"))" &
      become: YES
      ansible.builtin.systemd:
        name: shinyApp
        state: started
        daemon_reload: yes
        enabled: yes
      tags: systemd

    - name: Check if port "{{ shinyApp_port }}" is listening -- doesn't return from previous nuhup
      wait_for:
        port: "{{ shinyApp_port }}"
        delay: 5
        timeout: 10
        msg: "Timeout waiting for port {{ shinyApp_port }} to respond"
      register: port_check
      ignore_errors: no

...
